version: '3.0'
services:

  mongodb:
    container_name: inviecom_beta_mongodb
    image: mongo
    restart: always
    ports:
      - "27031:27017"
    networks:
      - default-network
    volumes:
      - ./backend/mongoims-backup:/data/db
  backend: 
    image: ghcr.io/ashish8800/inviecom_beta-backend:v1.0.0
    container_name: inviEcom_beta_backend
    env_file:
      - backend/.env
    restart: on-failure
    networks:
      - default-network
      - gem_frontend-network    
    ports:
     - "5106:5106"
  frontend:
    image: ghcr.io/ashish8800/inviecom_beta-frontend:v1.0.0
    container_name: inviEcom_beta_frontend
    env_file:
      - frontend/.env
    depends_on:
      - backend
    restart: on-failure
    networks:
      - gem_frontend-network    
    ports:
      - "3106:3106"           

      
networks:
  default-network:
  gem_frontend-network:
