version: '3.0'
services:
  backend: 
    image: ghcr.io/ashish8800/inviecom2-backend
    container_name: inviEcom_backend 
    env_file:
       - ./backend/.env
    restart: on-failure
    ports:
     - "5106:5106"
  frontend:
    container_name: inviEcom_frontend
    image: ghcr.io/ashish8800/inviecom2-frontend
    env_file:
       - ./frontend/.env
    depends_on:
       - backend
      restart: on-failure    
    ports:
       - "3106:3106"           

      
